# Generated by Django 5.0.3 on 2024-03-31 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='singer',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist'),
            preserve_default=False,
        ),
    ]
