# Generated by Django 5.0.3 on 2024-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
