# Generated by Django 5.0.3 on 2024-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='scope',
            field=models.CharField(choices=[('L', 'Local'), ('N', 'Nacional'), ('I', 'Internacional')], default='I', max_length=1),
        ),
    ]
